global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

# This configuration tells Prometheus to scrape metrics from itself (prometheus:9090) and from the node-exporter running on your server (node-exporter:9100).